// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4fwbq2vHzCNaxOQTZYZ6mFeEpHTC-vmc',
    appId: '1:1011091797571:web:50d074a74263ea461586f6',
    messagingSenderId: '1011091797571',
    projectId: 'eventmanagement-bf32b',
    authDomain: 'eventmanagement-bf32b.firebaseapp.com',
    storageBucket: 'eventmanagement-bf32b.appspot.com',
    measurementId: 'G-YQTQXDX8LV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLxo7c1wuZ6VO8UR85EYImxOeirxggPa0',
    appId: '1:1011091797571:android:980968dfb9eca2191586f6',
    messagingSenderId: '1011091797571',
    projectId: 'eventmanagement-bf32b',
    storageBucket: 'eventmanagement-bf32b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm--yRVgbIUPpG7olRTanKfal5lBt1ezU',
    appId: '1:1011091797571:ios:2ffacb77a5c19a4f1586f6',
    messagingSenderId: '1011091797571',
    projectId: 'eventmanagement-bf32b',
    storageBucket: 'eventmanagement-bf32b.appspot.com',
    iosBundleId: 'com.example.eventmanagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm--yRVgbIUPpG7olRTanKfal5lBt1ezU',
    appId: '1:1011091797571:ios:43992867c35ab0aa1586f6',
    messagingSenderId: '1011091797571',
    projectId: 'eventmanagement-bf32b',
    storageBucket: 'eventmanagement-bf32b.appspot.com',
    iosBundleId: 'com.example.eventmanagement.RunnerTests',
  );
}
